if pocket then
	print("Welcome to the PDA_OS installation.")
	print("The installation process will begin...")
	print("--------------------------------------")
	print("Deleting old files...")
	shell.run("delete", "startup.lua")
	shell.run("delete", ".back")
	shell.run("delete", ".menu")
	shell.run("delete", "os")
	shell.run("delete", "programs")
	print("Creating and Downloading files...")
	sleep(3)
	shell.run("mkdir", "os")
	shell.run("mkdir", "programs")
	shell.run("wget", "https://github.com/MeLlamoGamer/PDA_OS-ComputerCraft/blob/main/startup.lua startup.lua")
	shell.run("wget", "https://github.com/MeLlamoGamer/PDA_OS-ComputerCraft/blob/main/.menu .menu")
	shell.run("wget", "https://github.com/MeLlamoGamer/PDA_OS-ComputerCraft/blob/main/.back .back")
	shell.run("wget", "https://github.com/MeLlamoGamer/PDA_OS-ComputerCraft/blob/main/programs/chat.lua programs/chat.lua")
	shell.run("wget", "https://github.com/MeLlamoGamer/PDA_OS-ComputerCraft/blob/main/programs/ftpcli.lua programs/ftpcli.lua")
	shell.run("wget", "https://github.com/MeLlamoGamer/PDA_OS-ComputerCraft/blob/main/os/.apps os/.apps")
	shell.run("wget", "https://github.com/MeLlamoGamer/PDA_OS-ComputerCraft/blob/main/os/.command os/.command")
	shell.run("wget", "https://github.com/MeLlamoGamer/PDA_OS-ComputerCraft/blob/main/os/.power os/.power")
	print("The installation finished successfully, rebooting...")
	sleep(3)
	os.reboot()
else
	print("This OS must run on a Pocket PC")
end